apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    service: node
spec:
  selector:
    app: node
  type: LoadBalancer
  loadBalancerIP: "34.27.20.205"
  ports:
    - port: 4000
      targetPort: 4000