apiVersion: v1
kind: Service
metadata:
  name: react-js
  labels:
    service: react-js
spec:
  selector:
    app: react-js
  type: LoadBalancer
  loadBalancerIP: "34.27.20.205"
  ports:
    - port: 3000
      targetPort: 3000